"""Real browser capturer (Playwright, human-in-the-loop).

Opens a real Chrome/Chromium with a persistent profile, lets the operator sign in
manually, then for each question: types the prompt into the real LLM UI, submits it,
waits for the real answer to finish streaming, reads the real answer text, and saves
a real full-page screenshot.

Evidence produced here is `browser` - it is a genuine capture of a real LLM UI.
Nothing is generated by the engine, and no login/CAPTCHA/rate limit is bypassed.

Playwright is imported lazily so the rest of the engine has no hard dependency on it.
"""

from __future__ import annotations

import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

from ..extractor import extract_urls
from .base import CaptureResult
from .selectors import model_config
from .session import connect_cdp, launch_context

# Streaming-settle tuning: the answer is considered complete when its text stops
# changing for STABLE_ROUNDS consecutive polls AND no "stop generating" control is
# visible. This is what makes an unattended capture trustworthy.
POLL_SECONDS = 1.5
STABLE_ROUNDS = 4
# Below this, an "answer" is almost certainly a citation/source fragment, not a real
# response. Matches the floor that capture-qa enforces, so the two agree.
MIN_ANSWER_CHARS = 80


class SelectorError(RuntimeError):
    """Raised when a configured selector does not match - names the key to fix."""


class PlaywrightCapturer:
    def __init__(
        self,
        model: str,
        headful: bool = True,
        login_wait: bool = False,
        answer_timeout_s: int = 180,
        confirm_each: bool = False,
        cdp_endpoint: str | None = None,
    ):
        self.model = model.lower()
        self.cfg = model_config(self.model)
        self.headful = headful
        self.login_wait = login_wait
        self.answer_timeout_s = answer_timeout_s
        self.confirm_each = confirm_each
        self.cdp_endpoint = cdp_endpoint
        self._pw = None
        self._ctx = None
        self._browser = None      # set only in CDP mode - the operator's browser
        self._attached = False    # true => never close the browser on exit
        self.page = None
        self.browser_label = ""

    # --- lifecycle ---------------------------------------------------------
    def __enter__(self):
        from playwright.sync_api import sync_playwright  # lazy

        self._pw = sync_playwright().start()
        if self.cdp_endpoint:
            self._ctx, self.browser_label, self._browser = connect_cdp(
                self._pw, self.cdp_endpoint)
            self._attached = True
            # Reuse a tab already on the model's site if the operator left one open -
            # that tab is the one that already passed verification.
            host = urlparse(self.cfg["url"]).netloc
            self.page = next(
                (p for p in self._ctx.pages if host in urlparse(p.url).netloc), None)
            if self.page is None:
                self.page = self._ctx.pages[0] if self._ctx.pages else self._ctx.new_page()
        else:
            self._ctx, self.browser_label = launch_context(
                self._pw, self.model, headful=self.headful)
            self.page = self._ctx.pages[0] if self._ctx.pages else self._ctx.new_page()

        self.page.set_default_timeout(30000)
        self.page.bring_to_front()
        if not self._on_model_site():
            self.page.goto(self.cfg["url"], wait_until="domcontentloaded")
        print(f"[{self.model}] browser={self.browser_label}  url={self.page.url[:70]}")

        if self.login_wait:
            print(f"[{self.model}] {self.cfg['login_hint']}")
            input(f"[{self.model}] Press Enter here once the chat UI is open and ready...")

        # Confirm the chat UI is actually usable before claiming we can capture.
        try:
            self.page.wait_for_selector(self.cfg["ready"], timeout=30000)
        except Exception as exc:  # noqa: BLE001
            if self._is_bot_challenge():
                raise SelectorError(
                    f"[{self.model}] BLOCKED by a bot-verification page "
                    f"(Cloudflare). This is the site's own protection and must NOT be "
                    f"bypassed. An operator has to clear it by hand:\n"
                    f"    python -m engine.main login --model {self.model}\n"
                    f"  complete the verification in the window, press Enter, then re-run\n"
                    f"  capture with --login-wait so you can clear it again if it reappears."
                ) from exc
            raise SelectorError(
                f"[{self.model}] chat UI not ready: selector 'ready' "
                f"({self.cfg['ready']!r}) never appeared. Either you are not signed in "
                f"(run: login --model {self.model}) or the selector needs updating in "
                f"engine/capture/selectors.py"
            ) from exc
        return self

    def __exit__(self, *exc):
        try:
            if self._attached:
                # The operator owns this Chrome. Detach only - closing it would throw
                # away the signed-in, human-verified session we depend on.
                if self._browser:
                    self._browser.close()  # disconnects the CDP client, leaves Chrome up
            elif self._ctx:
                self._ctx.close()
        except Exception:  # noqa: BLE001
            pass
        finally:
            if self._pw:
                self._pw.stop()

    def _on_model_site(self) -> bool:
        try:
            return urlparse(self.cfg["url"]).netloc in urlparse(self.page.url).netloc
        except Exception:  # noqa: BLE001
            return False

    # --- helpers -----------------------------------------------------------
    def _answer_text(self) -> str:
        """Text of the answer element that holds the MOST text.

        Not `.last`: several models render citation/source cards that also match the
        answer selector and appear later in the DOM. Taking the last match captured a
        95-char citation fragment from Perplexity instead of the answer. The answer
        body is reliably the largest matching block.
        """
        loc = self.page.locator(self.cfg["answer"])
        n = loc.count()
        if n == 0:
            return ""
        best = ""
        for i in range(max(0, n - 6), n):  # only the newest few; the transcript grows
            try:
                t = (loc.nth(i).inner_text() or "").strip()
            except Exception:  # noqa: BLE001 - element detached mid-stream
                continue
            if len(t) > len(best):
                best = t
        return best

    def _is_bot_challenge(self) -> bool:
        """True while a bot-verification interstitial is on screen."""
        try:
            title = (self.page.title() or "").lower()
            if "just a moment" in title or "attention required" in title:
                return True
            body = (self.page.locator("body").inner_text() or "").lower()[:400]
            return ("verifying you are human" in body
                    or "performing security verification" in body
                    or "checking your browser" in body)
        except Exception:  # noqa: BLE001
            return False

    def _is_streaming(self) -> bool:
        sel = self.cfg.get("streaming")
        if not sel:
            return False
        try:
            return self.page.locator(sel).first.is_visible(timeout=500)
        except Exception:  # noqa: BLE001 - not visible / detached
            return False

    def _submit(self, prompt: str) -> None:
        box = self.page.locator(self.cfg["input"]).first
        try:
            box.wait_for(state="visible", timeout=20000)
        except Exception as exc:  # noqa: BLE001
            raise SelectorError(
                f"[{self.model}] prompt box not found: selector 'input' "
                f"({self.cfg['input']!r}). Fix it in engine/capture/selectors.py"
            ) from exc
        box.click()
        # contenteditable boxes reject fill(); type() works for both.
        try:
            box.fill(prompt)
        except Exception:  # noqa: BLE001
            box.type(prompt, delay=5)

        # Click the send button only if it actually exists. Probing a zero-match
        # locator blocks for the full default timeout, so count() is checked first.
        submit_sel = self.cfg.get("submit")
        clicked = False
        if submit_sel and self.page.locator(submit_sel).count() > 0:
            try:
                btn = self.page.locator(submit_sel).first
                if btn.is_enabled(timeout=2000):
                    btn.click(timeout=5000)
                    clicked = True
            except Exception:  # noqa: BLE001 - fall through to Enter
                pass
        if not clicked:
            self.page.keyboard.press("Enter")

    def _wait_for_answer(self, before_count: int, before_text: str) -> str:
        """Block until a NEW assistant message stops changing, or timeout.

        A persistent profile can restore the previous conversation, so "an answer
        arrived" cannot be detected by message count alone - the count may already be
        non-zero and may not grow. We therefore treat EITHER a growing message count
        OR the answer text differing from the pre-submit baseline as the new answer.
        """
        deadline = time.time() + self.answer_timeout_s
        last, stable = "", 0

        # Phase 1: new assistant content must appear.
        while time.time() < deadline:
            loc = self.page.locator(self.cfg["answer"])
            n = loc.count()
            if n > before_count:
                break
            if n > 0:
                current = self._answer_text()
                if current and current != before_text:
                    break
            time.sleep(POLL_SECONDS)

        # Phase 2: wait for the text to settle and streaming to stop.
        while time.time() < deadline:
            text = self._answer_text()
            if text and text == before_text:
                # Still showing the restored/previous answer - not ours yet.
                stable = 0
            elif text and text == last:
                stable += 1
                if stable >= STABLE_ROUNDS and not self._is_streaming():
                    return text
            else:
                stable = 0
            last = text
            time.sleep(POLL_SECONDS)
        return last if last != before_text else ""

    # --- capture -----------------------------------------------------------
    def capture(self, question_id: int, prompt: str, screenshot_path: Path) -> CaptureResult:
        """Submit one real prompt, capture the real answer + a real screenshot."""
        try:
            # Reset to a normal window: a previous capture may have grown the
            # viewport to fit its answer.
            try:
                self.page.set_viewport_size({"width": 1440, "height": 900})
            except Exception:  # noqa: BLE001
                pass
            # Baseline BEFORE submitting, so a restored conversation is never
            # mistaken for this question's answer.
            before = self.page.locator(self.cfg["answer"]).count()
            before_text = self._answer_text() if before else ""
            submitted_at = datetime.now(timezone.utc)
            self._submit(prompt)
            answer = self._wait_for_answer(before, before_text)

            if self.confirm_each:
                input(f"[{self.model} q{question_id}] Answer captured "
                      f"({len(answer)} chars). Press Enter to screenshot + continue...")
                answer = self._answer_text() or answer

            if not answer:
                return CaptureResult(
                    question_id, self.model, ok=False,
                    notes=("no answer text: either generation timed out "
                           f"({self.answer_timeout_s}s) or selector 'answer' "
                           f"({self.cfg['answer']!r}) needs updating"),
                )
            # A too-short extraction means the selector matched a citation/source card
            # rather than the answer. Fail loudly instead of saving a fragment as proof.
            if len(answer) < MIN_ANSWER_CHARS:
                return CaptureResult(
                    question_id, self.model, ok=False,
                    notes=(f"extracted only {len(answer)} chars (min {MIN_ANSWER_CHARS}) - "
                           f"selector 'answer' ({self.cfg['answer']!r}) is probably matching a "
                           f"citation/source element, not the answer body. Fix it in "
                           f"engine/capture/selectors.py. Extract was: {answer[:80]!r}"),
                )

            shot = Path(screenshot_path)
            shot.parent.mkdir(parents=True, exist_ok=True)
            self._fit_viewport_to_conversation()
            self.page.screenshot(path=str(shot), full_page=True)

            width = height = 0
            try:  # record real render dimensions so QA can tell a real shot from a stub
                from PIL import Image

                with Image.open(shot) as im:
                    width, height = im.size
            except Exception:  # noqa: BLE001 - dimensions are informational
                pass

            return CaptureResult(
                question_id=question_id,
                model=self.model,
                ok=True,
                answer=answer,
                urls=extract_urls(answer),
                screenshot_path=str(shot),
                evidence_type="browser",
                notes="",
                submitted_prompt=prompt,
                page_url=self.page.url,
                captured_at=submitted_at.isoformat(timespec="seconds"),
                browser=self.browser_label,
                screenshot_bytes=shot.stat().st_size if shot.exists() else 0,
                screenshot_width=width,
                screenshot_height=height,
            )
        except SelectorError as exc:
            return CaptureResult(question_id, self.model, ok=False, notes=str(exc))
        except Exception as exc:  # noqa: BLE001 - never fabricate; record and continue
            return CaptureResult(question_id, self.model, ok=False, notes=f"capture error: {exc!r}")

    def _fit_viewport_to_conversation(self, max_height: int = 8000) -> None:
        """Grow the viewport so the whole conversation is visible in one screenshot.

        Chat UIs render the transcript inside their own scrolling container, so a
        plain full-page screenshot captures the page shell and clips the answer. We
        measure the tallest scrollable container, resize the viewport to it, and let
        the UI re-render - after which `full_page=True` shows the entire answer.
        """
        try:
            needed = self.page.evaluate(
                """() => {
                    let max = document.documentElement.scrollHeight || 0;
                    for (const el of document.querySelectorAll('*')) {
                        if (el.scrollHeight > el.clientHeight + 50 && el.clientHeight > 200) {
                            max = Math.max(max, el.scrollHeight + 200);
                        }
                    }
                    return max;
                }"""
            )
            height = max(900, min(int(needed or 900), max_height))
            self.page.set_viewport_size({"width": 1440, "height": height})
            self.page.wait_for_timeout(1200)  # let the UI reflow at the new height
            self.page.evaluate("window.scrollTo(0, 0)")
            self.page.wait_for_timeout(300)
        except Exception:  # noqa: BLE001 - screenshot still works at the default size
            pass

    def new_chat(self) -> None:
        """Start a clean conversation so answers are independent, not follow-ups."""
        try:
            self.page.goto(self.cfg["url"], wait_until="domcontentloaded")
            self.page.wait_for_selector(self.cfg["ready"], timeout=30000)
        except Exception:  # noqa: BLE001 - non-fatal; capture() re-checks
            pass
